AsmFinal/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AsmFinal.Models
{
    public class Enrollment
    {
        [Key]
        public int Id { get; set; }
        [Remote("IsProductNameExist", "Enrollment", AdditionalFields = "Id",
                ErrorMessage = "Enrollment name already exists")]
        public string Name { get; set; }
        public DateTime EnrollmentDateStarted { get; set; }
        public DateTime EnrollmentDateExpired { get; set; }
        
        public int CourseId { get; set; }
        public Course Course { get; set; }
        
        public int TraineeId { get; set; }
        public Trainee Trainee { get; set; }
        

    }
}

AsmFinal/Controllers/EnrollmentsController.cs
using AsmFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using AsmFinal.ViewModel;

namespace AsmFinal.Controllers
{
    [Authorize(Roles = "Staff,Trainee")]
    public class EnrollmentsController : Controller
    {
        private ApplicationDbContext _context;
        public EnrollmentsController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Products
        [HttpGet]
        public ActionResult Index()
        {
            var list = _context.Enrollments.Include(p => p.Course).ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult Create()
        {

            var viewModel = new EnrollmentCourseViewModel();
            viewModel.Courses = _context.Courses.ToList();
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Create(Enrollment enrollment)
        {
            bool IsProductNameExist = _context.Enrollments.Any
                    (x => x.Name == enrollment.Name && x.Id != enrollment.Id);
            if (IsProductNameExist == true)
            {
                ModelState.AddModelError("Name", "Enrollment Name already exists");
            }
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create");
            }
            _context.Enrollments.Add(enrollment);
            _context.SaveChanges();
            return RedirectToAction("Index");


        }
        public ActionResult Delete(int id)
        {
            var productInDb = _context.Enrollments.SingleOrDefault(p => p.Id == id);

            if (productInDb == null)
            {
                return HttpNotFound();
            }

            _context.Enrollments.Remove(productInDb);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var CourseInDb = _context.Enrollments.SingleOrDefault(m => m.Id == id);
            if (CourseInDb == null) return HttpNotFound();

            var viewModel = new EnrollmentCourseViewModel()
            {
                Courses = _context.Courses.ToList(),
                Enrollment = CourseInDb
            };

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult Edit(Enrollment enrollment)
        {
            bool IsProductNameExist = _context.Enrollments.Any
                               (x => x.Name == enrollment.Name && x.Id != enrollment.Id);
            if (IsProductNameExist == true)
            {
                ModelState.AddModelError("Name", "Enrollment Name already exists");
            }
            var CourseInDb = _context.Enrollments.SingleOrDefault(m => m.Id == enrollment.Id);
            CourseInDb.EnrollmentDateExpired = enrollment.EnrollmentDateExpired;
            CourseInDb.EnrollmentDateStarted = enrollment.EnrollmentDateStarted;
            CourseInDb.CourseId = enrollment.CourseId;

            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public JsonResult IsProductNameExist(string ProductName, int? Id)
        {
            var validateName = _context.Enrollments.FirstOrDefault
                                (x => x.Name == ProductName && x.Id != Id);
            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

AsmFinal/Controllers/TopicsController.cs
using AsmFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using AsmFinal.ViewModel;
using Microsoft.AspNet.Identity;

namespace AsmFinal.Controllers
{
    [Authorize(Roles = "Staff,Trainer")]
    public class TopicsController : Controller
    {
        private ApplicationDbContext _context;
        public TopicsController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Products
        [HttpGet]
        public ActionResult Index()
        {
            var list = _context.Topics.Include(p => p.Course).ToList();
            
            
            return View(list);

        }
        [HttpGet]
        public ActionResult Create()
        {

            var viewModel = new TopicCourseViewModel();
            viewModel.Courses = _context.Courses.ToList();
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Create(Topic topic)
        {
            bool IsProductNameExist = _context.Topics.Any
                   (x => x.Name == topic.Name && x.Id != topic.Id);
            if (IsProductNameExist == true)
            {
                ModelState.AddModelError("Name", "Topic Name already exists");
            }
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create");
            }
            _context.Topics.Add(topic);
            _context.SaveChanges();
            return RedirectToAction("Index");


        }
        public ActionResult Delete(int id)
        {
            var productInDb = _context.Topics.SingleOrDefault(p => p.Id == id);

            if (productInDb == null)
            {
                return HttpNotFound();
            }

            _context.Topics.Remove(productInDb);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var CourseInDb = _context.Topics.SingleOrDefault(m => m.Id == id);
            if (CourseInDb == null) return HttpNotFound();

            var viewModel = new TopicCourseViewModel()
            {
                Courses = _context.Courses.ToList(),
                Topic = CourseInDb
            };

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult Edit(Topic topic)
        {
            bool IsProductNameExist = _context.Topics.Any
                              (x => x.Name == topic.Name && x.Id != topic.Id);
            if (IsProductNameExist == true)
            {
                ModelState.AddModelError("Name", "Topic Name already exists");
            }
            var CourseInDb = _context.Topics.SingleOrDefault(m => m.Id == topic.Id);
            CourseInDb.Name = topic.Name;
            CourseInDb.Detail = topic.Detail;
            CourseInDb.CourseId = topic.CourseId;

            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public JsonResult IsProductNameExist(string ProductName, int? Id)
        {
            var validateName = _context.Topics.FirstOrDefault
                                (x => x.Name == ProductName && x.Id != Id);
            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

AsmFinal/Views/Enrollments/Create.cshtml
@model AsmFinal.ViewModel.EnrollmentCourseViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create </h2>

@using (Html.BeginForm("Create", "Enrollments", FormMethod.Post))
{
    @Html.LabelFor(p => p.Enrollment.Name)
    @Html.TextBoxFor(p => p.Enrollment.Name, new { @class = "form-control" })
    @Html.ValidationMessageFor(p => p.Enrollment.Name)

    @Html.LabelFor(p => p.Enrollment.EnrollmentDateStarted)
    @Html.TextBoxFor(p => p.Enrollment.EnrollmentDateStarted, new { @class = "form-control" })
    @Html.ValidationMessageFor(p => p.Enrollment.EnrollmentDateStarted)
    @Html.LabelFor(p => p.Enrollment.EnrollmentDateExpired)
    @Html.TextBoxFor(p => p.Enrollment.EnrollmentDateExpired, new { @class = "form-control" })
    @Html.ValidationMessageFor(p => p.Enrollment.EnrollmentDateExpired)
    @Html.LabelFor(p => p.Enrollment.Course.Name)
    @Html.DropDownListFor(p => p.Enrollment.CourseId, new SelectList(Model.Courses, "Id", "Name"), "Select Course Name",
        new { @class = "form-control" })

    <input type="submit" value="Submit" class="btn-primary" />
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

AsmFinal/Views/Enrollments/Edit.cshtml
@model AsmFinal.ViewModel.EnrollmentCourseViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit </h2>

@using (Html.BeginForm("Edit", "Topics", FormMethod.Post))
{
    @Html.HiddenFor(p => p.Enrollment.Id)
    @Html.LabelFor(p => p.Enrollment.Name)
    @Html.EditorFor(p => p.Enrollment.Name, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(p => p.Enrollment.Name)
    @Html.LabelFor(p => p.Enrollment.EnrollmentDateStarted)
    @Html.EditorFor(p => p.Enrollment.EnrollmentDateStarted, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(p => p.Enrollment.EnrollmentDateStarted)
    @Html.LabelFor(p => p.Enrollment.EnrollmentDateExpired)
    @Html.EditorFor(p => p.Enrollment.EnrollmentDateExpired, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(p => p.Enrollment.EnrollmentDateExpired)
    @Html.LabelFor(p => p.Enrollment.Course.Name)
    @Html.DropDownListFor(p => p.Enrollment.CourseId, new SelectList(Model.Courses, "Id", "Name"), "Select Category Name",
        new { @class = "form-control" })
    <input type="submit" value="Submit" class="btn-primary" />
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

AsmFinal/Views/Enrollments/Index.cshtml
@model IEnumerable<AsmFinal.Models.Enrollment>
@{
    ViewBag.Title = "Index";
}

<h2> Enrollment</h2>
@if (User.IsInRole("Staff"))
{@Html.ActionLink("Create New", "Create")}

<table class="table">
    <td width="200"><b>Enrollment Name</b></td>
    <td width="200"><b> Enrollment DateStarted </b></td>
    <td width="200"><b>Enrollment DateExpired</b></td>
    <td width="200"><b>Course Name</b></td>
    <td></td>
</table>
@foreach (var p in Model)
{
<table class="table">
    <td class="alignCenter" width="200">@p.Name</td>
    <td class="alignCenter" width="200">@p.EnrollmentDateStarted</td>
    <td class="alignCenter" width="200">@p.EnrollmentDateExpired</td>
    <td class="alignCenter" width="200">@p.Course.Name</td>
    @if (User.IsInRole("Staff"))
    { <td>
    @Html.ActionLink("Edit", "Edit", new { id = p.Id }) |
    @Html.ActionLink("Delete", "Delete", new { id = p.Id })
</td>}

</table>

}