AsmFinal/Controllers/CoursesController.cs
using AsmFinal.Models;
using AsmFinal.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace AsmFinal.Controllers
{
    [Authorize(Roles = "Staff")]
    public class CoursesController : Controller
    {
        private ApplicationDbContext _context;
        public CoursesController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Products
        [HttpGet]
        public ActionResult Index()
        {
            var list = _context.Courses.Include(p=>p.Category).ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult Create()
        {

            var viewModel = new CourseCategoryViewModel();
            viewModel.Categories = _context.Categories.ToList();
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Create(Course course)
        {
            bool IsCourseNameExist = _context.Courses.Any
                   (x => x.Name == course.Name && x.Id != course.Id);
            if (IsCourseNameExist == true)
            {
                ModelState.AddModelError("Name", "Course Name already exists");
            }
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create");
            }
            _context.Courses.Add(course);
            _context.SaveChanges();
            return RedirectToAction("Index");


        }
        public ActionResult Delete(int id)
        {
            var productInDb = _context.Courses.SingleOrDefault(p => p.Id == id);

            if (productInDb == null)
            {
                return HttpNotFound();
            }

            _context.Courses.Remove(productInDb);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {

            var CourseInDb = _context.Courses.SingleOrDefault(m => m.Id == id);
            if (CourseInDb == null) return HttpNotFound();

            var viewModel = new CourseCategoryViewModel()
            {
                Categories = _context.Categories.ToList(),
                Course = CourseInDb
            };

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult Edit(Course course)
        {
            bool IsCourseNameExist = _context.Courses.Any
                           (x => x.Name == course.Name && x.Id != course.Id);
            if (IsCourseNameExist == true)
            {
                ModelState.AddModelError("Name", "Course Name already exists");
            }
            var CourseInDb = _context.Courses.SingleOrDefault(m => m.Id == course.Id);
            CourseInDb.Name = course.Name;
            CourseInDb.Detail = course.Detail;
            CourseInDb.CategoryId = course.CategoryId;

            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public JsonResult IsCourseNameExist(string ProductName, int? Id)
        {
            var validateName = _context.Courses.FirstOrDefault
                                (x => x.Name == ProductName && x.Id != Id);
            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

AsmFinal/Controllers/TopicsController.cs
using AsmFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using AsmFinal.ViewModel;
using Microsoft.AspNet.Identity;

namespace AsmFinal.Controllers
{
    [Authorize(Roles = "Staff,Trainer")]
    public class TopicsController : Controller
    {
        private ApplicationDbContext _context;
        public TopicsController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Products
        [HttpGet]
        public ActionResult Index()
        {
            var list = _context.Topics.Include(p => p.Course).ToList();
            
            
            return View(list);

        }
        [HttpGet]
        public ActionResult Create()
        {

            var viewModel = new TopicCourseViewModel();
            viewModel.Courses = _context.Courses.ToList();
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Create(Topic topic)
        {
            bool IsProductNameExist = _context.Topics.Any
                   (x => x.Name == topic.Name && x.Id != topic.Id);
            if (IsProductNameExist == true)
            {
                ModelState.AddModelError("Name", "Topic Name already exists");
            }
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create");
            }
            _context.Topics.Add(topic);
            _context.SaveChanges();
            return RedirectToAction("Index");


        }
        public ActionResult Delete(int id)
        {
            var productInDb = _context.Topics.SingleOrDefault(p => p.Id == id);

            if (productInDb == null)
            {
                return HttpNotFound();
            }

            _context.Topics.Remove(productInDb);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var CourseInDb = _context.Topics.SingleOrDefault(m => m.Id == id);
            if (CourseInDb == null) return HttpNotFound();

            var viewModel = new TopicCourseViewModel()
            {
                Courses = _context.Courses.ToList(),
                Topic = CourseInDb
            };

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult Edit(Topic topic)
        {
            bool IsProductNameExist = _context.Topics.Any
                              (x => x.Name == topic.Name && x.Id != topic.Id);
            if (IsProductNameExist == true)
            {
                ModelState.AddModelError("Name", "Topic Name already exists");
            }
            var CourseInDb = _context.Topics.SingleOrDefault(m => m.Id == topic.Id);
            CourseInDb.Name = topic.Name;
            CourseInDb.Detail = topic.Detail;
            CourseInDb.CourseId = topic.CourseId;

            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public JsonResult IsProductNameExist(string ProductName, int? Id)
        {
            var validateName = _context.Topics.FirstOrDefault
                                (x => x.Name == ProductName && x.Id != Id);
            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

AsmFinal/Controllers/UsersController.cs
using AsmFinal.Models;
using AsmFinal.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Assignment.Controllers
{
    public class UsersController : Controller
    {


        private ApplicationDbContext _context;

        

        public UsersController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Users

        // GET: Users
        public ActionResult Index()
        {
          var usersWithRoles = (from user in _context.Users
                                  select new
                                  {
                                      Username = user.UserName,
                                      Email = user.Email,
                                      RoleNames = (from userRole in user.Roles
                                                   join role in _context.Roles on userRole.RoleId equals role.Id
                                                   select role.Name).ToList()
                                  }).ToList().Select(p => new UserViewModel()

                                  {
                                      Username = p.Username,
                                      Email = p.Email,
                                      Role = string.Join(",", p.RoleNames)
                                  });
            return View(usersWithRoles);
        }

        public ActionResult Delete(string id)
        {
            var productInDb = _context.Users.SingleOrDefault(p => p.Id == id);

            if (productInDb == null)
            {
                return HttpNotFound();
            }

            _context.Users.Remove(productInDb);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
       
        }
    }

AsmFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Student Managerment", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    
                    @if (Request.IsAuthenticated && User.IsInRole("Trainer"))
                    {

                        <li>@Html.ActionLink("Trainer", "Index", "TrainerTopics")</li>
                        <li>@Html.ActionLink("Course", "Index", "Courses")</li>
                        <li>@Html.ActionLink("Topic", "Index", "Topics")</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Trainee"))
                    {

                        <li>@Html.ActionLink("Trainee", "Index", "TraineeEnrollments")</li>
                        <li>@Html.ActionLink("Enrollment", "Index", "Enrollments")</li>

                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Staff"))
                    {
                        <li>@Html.ActionLink("Trainer", "Index", "TrainerTopics")</li>
                        <li>@Html.ActionLink("Course", "Index", "Courses")</li>
                        <li>@Html.ActionLink("Topic", "Index", "Topics")</li>
                        <li>@Html.ActionLink("Enrollment", "Index", "Enrollments")</li>
                        <li>@Html.ActionLink("Category", "Index", "Categories")</li>
                        <li>@Html.ActionLink("Trainee", "Index", "TraineeEnrollments")</li>
                        <li>@Html.ActionLink("Register", "Register", "Account")</li>
                    }

                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("User", "Index", "Users")</li>
                        <li>@Html.ActionLink("Role", "Index", "Role")</li>
                        <li>@Html.ActionLink("Register", "Register", "Account")</li>

                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>